### ISSUE TITLE
Encountering Authentication Issues

### ISSUE THREAD

**Issue by LM-01** [katanaml/katana-skipper#7]
When I run the start command on docker I get the following error in the data-service container.  Would greatly appreciate guidance on how to fix this issue.
`
data-service
[katanaml/data-service](https://github.com/katanaml/katana-skipper/issues/new)
RUNNING

Traceback (most recent call last):

  File "main.py", line 19, in <module>

    main()

  File "main.py", line 15, in main

    'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))

  File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 16, in __init__

    credentials=credentials))

  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__

    self._impl = self._create_connection(parameters, _impl_class)

  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection

    raise self._reap_last_connection_workflow_error(error)

pika.exceptions.AMQPConnectionError

Traceback (most recent call last):

  File "main.py", line 19, in <module>

    main()

  File "main.py", line 15, in main

    'http://127.0.0.1:5001/api/v1/skipper/logger/log_receiver'))

  File "/usr/local/lib/python3.7/site-packages/skipper_lib/events/event_receiver.py", line 16, in __init__

    credentials=credentials))

  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__

    self._impl = self._create_connection(parameters, _impl_class)

  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection

    raise self._reap_last_connection_workflow_error(error)

pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfi`

**Comment by abaranovskis-redsamurai** [comment]
Hi,

You can ignore this error. RabbitMQ service is not ready yet, when Data service is trying to connect. But Data service will auto restart and the next attempts it will establish connection. Wait around 10 seconds and run docker ps -a, you should see all containers up.

**Comment by LM-01** [comment]
Thanks for the response quick response. There was no issue after it loaded properly. I love this project, thank you and the collaborators for putting it together!

**Comment by abaranovskis-redsamurai** [comment]
Thanks a lot for your feedback! :) There are future improvements and additions planned. We are using this platform for our own ML products and planning to improve the platform, as we go along.
